version: '3.8'

services:
  db:
    image: mysql
    restart: on-failure
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=restaurant
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - restaurant

volumes:
  db_data:

networks:
  restaurant:
    driver: bridge
